### ISSUE TITLE
Remove param_validations gem

### ISSUE THREAD

**Issue by orlando** [debtcollective/fundraising#20]
**What:** Remove param_validations gem

**Why:** Since we are moving to use strong_params in #16, this gem won't be needed

**How:**

- Remove the gem and keep the application working correctly.

**Comment by castrolem** [comment]
@orlando investigated more on this one, this is a custom gem that no longer exists. It's being used for param validation on stripe operations and a few other validations, it's well tested and does not need to be changed even if we change to the latest version of the stripe API because it's very generic.

I asked Eric about it, and he told me the history of the gem (that's how I know it used to be a gem). I will dig more about it and will update the story with it.

**Comment by castrolem** [comment]
Will verify the inner functions and the way the data is handled by this gem today.

**Comment by castrolem** [comment]
All test are green, validators are quite simple. There's no odd data handling or mutations happening within the gem, let's keep it.
